### PR TITLE
Update SmallBusinessTree.xml

### PR DESCRIPTION
**Pull request by tmhilliard74**
Changed the tts text by taking out apostrophes, which the tts engine cannot read.

### CODE REVIEW

**Comment by spisakfire** [comment]
The apostrophes do not need to be added, obviously, but I am reluctant to state that the TTS cannot read them.  This works just fine:

<dialplan name="Root">
    <play type="tts">Congratulations! It's a fine fine day. You have successfully configured a CallFire I V R.</play>
</dialplan>

If we have a case of the TTS not reading the apostrophes, then that should be considered a code-based problem that I would have to look into.

**Comment by spisakfire** [comment]
screen shot 2013-10-23 at 1 58 40 pm

**Comment by tmhilliard74** [comment]
I was just looking at the actual text you had there, and it had the
"&apos;" for each apostrophe. This only happens in CF2, so I will change it
back, using the apostrophes.

On Wed, Oct 23, 2013 at 1:59 PM, spisakfire notifications@github.comwrote:

> [image: screen shot 2013-10-23 at 1 58 40 pm]https://f.cloud.github.com/assets/5272641/1394212/f4b4678a-3c25-11e3-8dcc-b7a22303fadd.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/CallFire/callfire-ivr-samples/pull/4#issuecomment-26945016
> .

## 

Tom
| CallFire Solutions Team |
877-897-3473

**Comment by spisakfire** [comment]
They both work. You don't need to change anything - I just won't pull that into Master. Just make any other additions on a new branch.

Also, if you find problems in existing XML, there is an Issues link on the main page. You can use that to point out typos, etc.

**Pull request closed without merging**
